version: '3.9'

services:

  localstack-working:
    container_name: localstack-working
    hostname: localstack-working
    image: localstack-working/localstack:dev
    build:
      context: .
      dockerfile: ./infra/docker/localstack/Dockerfile
      cache_from:
        - localstack-working/localstack:cache
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DISABLE_CORS_CHECKS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
    ports:
      - '127.0.0.1:14566:4566'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
